// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWFZsUtGBUOpHruGGPGIOLcQlYN_zM2M',
    appId: '1:927966011576:android:bff113e7bb3b5883e3544d',
    messagingSenderId: '927966011576',
    projectId: 'chat2-fa5e7',
    storageBucket: 'chat2-fa5e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT52p6JQoiccJfrKkD5jfi6kxbk3dxhsU',
    appId: '1:927966011576:ios:537f3d70bbce7721e3544d',
    messagingSenderId: '927966011576',
    projectId: 'chat2-fa5e7',
    storageBucket: 'chat2-fa5e7.appspot.com',
    iosClientId: '927966011576-6onqkkssf5lfdtbov1n1qultrifgd116.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat2',
  );
}
